export const types ={
    newTASK:'[Task] create',
    TASK_NEW:'[Task] TASK_NEW',
    
    TASK_FETCH_REQUEST:'[Task] TASK_FETCH_REQUEST',
    TASK_FETCH_SUCCESS:'[Task] TASK_FETCH_SUCCESS',

    TASK_SAVE_REQUEST:'[Task] TASK_SAVE_REQUEST',
    TASK_SAVE_SUCCESS:'[Task] TASK_SAVE_SUCCESS',
    TASK_LOAD_REQUEST:'[Task] TASK_LOAD_REQUEST',
    TASK_LOAD_SUCCESS:'[Task] TASK_LOAD_SUCCESS',
    TASK_EDIT_REQUEST:'[Task] TASK_EDIT_REQUEST',

    

    //----UI REDUCER  - TYPES
    UI_LOADING_REQUEST:'[UI] UI_LOADING_REQUEST',
    UI_LOADING_SUCCESS:'[UI] UI_LOADING_SUCCESS',
    UI_LOADING_ERROR:'[UI] UI_LOADING_ERROR',


    UI_SHOW_SUCCESS_MESSAGGE:'[UI] UI_SHOW_SUCCESS_MESSAGGE',
    UI_SHOW_ERROR_MESSAGGE:'[UI] UI_SHOW_ERROR_MESSAGGE',


}